// Curated iconic species (icons + classic model organisms) that the Wikipedia-first
// pull can't reach because their article lives on a NON-TAXON Wikidata item (house
// cat -> "Cat", horse, cattle, grape, coconut...). Extracted from the retired
// build-taxonomy.mjs; consumed by scripts/inject-extras.mjs.

export const EXTRAS = [
  // Humans + classic lab model organisms
  { name: "Homo sapiens", common: "Human" },
  { name: "Mus musculus", common: "House mouse" },
  { name: "Rattus norvegicus", common: "Brown rat" },
  { name: "Danio rerio", common: "Zebrafish" },
  { name: "Gallus gallus", common: "Chicken" },
  { name: "Xenopus laevis", common: "African clawed frog" },
  { name: "Drosophila melanogaster", common: "Fruit fly" },
  { name: "Caenorhabditis elegans", common: "Roundworm" },
  { name: "Apis mellifera", common: "Western honey bee" },
  { name: "Saccharomyces cerevisiae", common: "Brewer's yeast" },
  { name: "Arabidopsis thaliana", common: "Thale cress" },
  { name: "Nematostella vectensis", common: "Starlet sea anemone" },
  { name: "Physcomitrium patens", common: "Spreading earthmoss" },
  { name: "Dictyostelium discoideum", common: "Slime mould" },
  { name: "Escherichia coli", common: "E. coli" },
  // Charismatic / phylogenetically fun tips
  { name: "Ambystoma mexicanum", common: "Axolotl" },
  { name: "Ornithorhynchus anatinus", common: "Platypus" },
  { name: "Sphenodon punctatus", common: "Tuatara" },
  { name: "Latimeria chalumnae", common: "Coelacanth" },
  { name: "Enteroctopus dofleini", common: "Giant Pacific octopus" },
  { name: "Architeuthis dux", common: "Giant squid" },
  { name: "Chelonia mydas", common: "Green sea turtle" },
  { name: "Danaus plexippus", common: "Monarch butterfly" },
  { name: "Phascolarctos cinereus", common: "Koala" },
  { name: "Milnesium tardigradum", common: "Water bear" },

  // ---- Culturally famous species (the "everyone knows these" set) ----
  // Big cats & other cats
  { name: "Panthera leo", common: "Lion" },
  { name: "Panthera tigris", common: "Tiger" },
  { name: "Panthera pardus", common: "Leopard" },
  { name: "Panthera onca", common: "Jaguar" },
  { name: "Panthera uncia", common: "Snow leopard" },
  { name: "Acinonyx jubatus", common: "Cheetah" },
  { name: "Puma concolor", common: "Cougar" },
  { name: "Felis catus", common: "Domestic cat" },
  { name: "Lynx lynx", common: "Eurasian lynx" },
  // Canids
  // (Domestic dog is Canis lupus familiaris — the same Open Tree tip as the wolf,
  //  so it can't be a distinct leaf here; "Gray wolf" stands in for the lineage.)
  { name: "Canis lupus", common: "Gray wolf" },
  { name: "Canis latrans", common: "Coyote" },
  { name: "Vulpes vulpes", common: "Red fox" },
  { name: "Vulpes lagopus", common: "Arctic fox" },
  { name: "Vulpes zerda", common: "Fennec fox" },
  { name: "Lycaon pictus", common: "African wild dog" },
  // Bears & other carnivores
  { name: "Ursus arctos", common: "Brown bear" },
  { name: "Ursus maritimus", common: "Polar bear" },
  { name: "Ursus americanus", common: "American black bear" },
  { name: "Ailuropoda melanoleuca", common: "Giant panda" },
  { name: "Ailurus fulgens", common: "Red panda" },
  { name: "Procyon lotor", common: "Raccoon" },
  { name: "Suricata suricatta", common: "Meerkat" },
  { name: "Meles meles", common: "European badger" },
  { name: "Lutra lutra", common: "European otter" },
  { name: "Enhydra lutris", common: "Sea otter" },
  { name: "Mephitis mephitis", common: "Striped skunk" },
  { name: "Crocuta crocuta", common: "Spotted hyena" },
  // Primates
  { name: "Pan troglodytes", common: "Chimpanzee" },
  { name: "Pan paniscus", common: "Bonobo" },
  { name: "Gorilla gorilla", common: "Western gorilla" },
  { name: "Pongo pygmaeus", common: "Bornean orangutan" },
  { name: "Hylobates lar", common: "Lar gibbon" },
  { name: "Papio anubis", common: "Olive baboon" },
  { name: "Mandrillus sphinx", common: "Mandrill" },
  { name: "Macaca mulatta", common: "Rhesus macaque" },
  { name: "Lemur catta", common: "Ring-tailed lemur" },
  // Large herbivores & hoofed mammals
  { name: "Loxodonta africana", common: "African bush elephant" },
  { name: "Elephas maximus", common: "Asian elephant" },
  { name: "Ceratotherium simum", common: "White rhinoceros" },
  { name: "Diceros bicornis", common: "Black rhinoceros" },
  { name: "Hippopotamus amphibius", common: "Hippopotamus" },
  { name: "Giraffa camelopardalis", common: "Giraffe" },
  { name: "Equus quagga", common: "Plains zebra" },
  { name: "Equus caballus", common: "Horse" },
  { name: "Equus asinus", common: "Donkey" },
  { name: "Bos taurus", common: "Cattle" },
  { name: "Bison bison", common: "American bison" },
  { name: "Bubalus bubalis", common: "Water buffalo" },
  { name: "Sus scrofa", common: "Wild boar" },
  { name: "Ovis aries", common: "Sheep" },
  { name: "Capra hircus", common: "Goat" },
  { name: "Alces alces", common: "Moose" },
  { name: "Rangifer tarandus", common: "Reindeer" },
  { name: "Cervus elaphus", common: "Red deer" },
  { name: "Odocoileus virginianus", common: "White-tailed deer" },
  { name: "Camelus dromedarius", common: "Dromedary" },
  { name: "Camelus bactrianus", common: "Bactrian camel" },
  { name: "Lama glama", common: "Llama" },
  { name: "Vicugna pacos", common: "Alpaca" },
  { name: "Connochaetes taurinus", common: "Blue wildebeest" },
  { name: "Aepyceros melampus", common: "Impala" },
  { name: "Phacochoerus africanus", common: "Warthog" },
  { name: "Oryctolagus cuniculus", common: "European rabbit" },
  // Other mammals
  { name: "Osphranter rufus", common: "Red kangaroo" },
  { name: "Vombatus ursinus", common: "Common wombat" },
  { name: "Sarcophilus harrisii", common: "Tasmanian devil" },
  { name: "Bradypus variegatus", common: "Brown-throated sloth" },
  { name: "Dasypus novemcinctus", common: "Nine-banded armadillo" },
  { name: "Myrmecophaga tridactyla", common: "Giant anteater" },
  { name: "Erinaceus europaeus", common: "European hedgehog" },
  { name: "Castor canadensis", common: "American beaver" },
  { name: "Orycteropus afer", common: "Aardvark" },
  // Marine mammals
  { name: "Tursiops truncatus", common: "Bottlenose dolphin" },
  { name: "Orcinus orca", common: "Orca" },
  { name: "Balaenoptera musculus", common: "Blue whale" },
  { name: "Megaptera novaeangliae", common: "Humpback whale" },
  { name: "Physeter macrocephalus", common: "Sperm whale" },
  { name: "Monodon monoceros", common: "Narwhal" },
  { name: "Delphinapterus leucas", common: "Beluga" },
  { name: "Odobenus rosmarus", common: "Walrus" },
  { name: "Phoca vitulina", common: "Harbor seal" },
  { name: "Trichechus manatus", common: "West Indian manatee" },
  { name: "Zalophus californianus", common: "California sea lion" },
  // Birds
  { name: "Haliaeetus leucocephalus", common: "Bald eagle" },
  { name: "Aquila chrysaetos", common: "Golden eagle" },
  { name: "Falco peregrinus", common: "Peregrine falcon" },
  { name: "Tyto alba", common: "Barn owl" },
  { name: "Bubo bubo", common: "Eurasian eagle-owl" },
  { name: "Aptenodytes forsteri", common: "Emperor penguin" },
  { name: "Spheniscus demersus", common: "African penguin" },
  { name: "Struthio camelus", common: "Common ostrich" },
  { name: "Dromaius novaehollandiae", common: "Emu" },
  { name: "Phoenicopterus roseus", common: "Greater flamingo" },
  { name: "Pavo cristatus", common: "Indian peafowl" },
  { name: "Cygnus olor", common: "Mute swan" },
  { name: "Anas platyrhynchos", common: "Mallard" },
  { name: "Ramphastos toco", common: "Toco toucan" },
  { name: "Ara macao", common: "Scarlet macaw" },
  { name: "Melopsittacus undulatus", common: "Budgerigar" },
  { name: "Corvus corax", common: "Common raven" },
  { name: "Columba livia", common: "Rock dove" },
  { name: "Erithacus rubecula", common: "European robin" },
  { name: "Alcedo atthis", common: "Common kingfisher" },
  { name: "Pelecanus onocrotalus", common: "Great white pelican" },
  { name: "Ciconia ciconia", common: "White stork" },
  { name: "Meleagris gallopavo", common: "Wild turkey" },
  { name: "Archilochus colubris", common: "Ruby-throated hummingbird" },
  // Reptiles & amphibians
  { name: "Crocodylus niloticus", common: "Nile crocodile" },
  { name: "Alligator mississippiensis", common: "American alligator" },
  { name: "Ophiophagus hannah", common: "King cobra" },
  { name: "Naja naja", common: "Indian cobra" },
  { name: "Python regius", common: "Ball python" },
  { name: "Boa constrictor", common: "Boa constrictor" },
  { name: "Crotalus atrox", common: "Western diamondback rattlesnake" },
  { name: "Eunectes murinus", common: "Green anaconda" },
  { name: "Varanus komodoensis", common: "Komodo dragon" },
  { name: "Iguana iguana", common: "Green iguana" },
  { name: "Chamaeleo chamaeleon", common: "Common chameleon" },
  { name: "Chelonoidis niger", common: "Galápagos tortoise" },
  { name: "Bufo bufo", common: "Common toad" },
  { name: "Dendrobates tinctorius", common: "Dyeing poison dart frog" },
  // Fish
  { name: "Carcharodon carcharias", common: "Great white shark" },
  { name: "Rhincodon typus", common: "Whale shark" },
  { name: "Sphyrna mokarran", common: "Great hammerhead" },
  { name: "Amphiprion ocellaris", common: "Clownfish" },
  { name: "Carassius auratus", common: "Goldfish" },
  { name: "Salmo salar", common: "Atlantic salmon" },
  { name: "Thunnus thynnus", common: "Atlantic bluefin tuna" },
  { name: "Xiphias gladius", common: "Swordfish" },
  { name: "Pygocentrus nattereri", common: "Red-bellied piranha" },
  { name: "Mobula birostris", common: "Giant manta ray" },
  { name: "Electrophorus electricus", common: "Electric eel" },
  { name: "Betta splendens", common: "Siamese fighting fish" },
  { name: "Sphyraena barracuda", common: "Great barracuda" },
  { name: "Gadus morhua", common: "Atlantic cod" },
  // Invertebrates
  { name: "Latrodectus mactans", common: "Southern black widow" },
  { name: "Mantis religiosa", common: "European mantis" },
  { name: "Coccinella septempunctata", common: "Seven-spot ladybird" },
  { name: "Homarus americanus", common: "American lobster" },
  { name: "Callinectes sapidus", common: "Blue crab" },
  { name: "Octopus vulgaris", common: "Common octopus" },
  { name: "Cornu aspersum", common: "Garden snail" },
  { name: "Periplaneta americana", common: "American cockroach" },
  { name: "Papilio machaon", common: "Old World swallowtail" },
  { name: "Photinus pyralis", common: "Common eastern firefly" },
  // Plants
  { name: "Helianthus annuus", common: "Sunflower" },
  { name: "Rosa canina", common: "Dog rose" },
  { name: "Quercus robur", common: "English oak" },
  { name: "Acer saccharum", common: "Sugar maple" },
  { name: "Sequoiadendron giganteum", common: "Giant sequoia" },
  { name: "Dionaea muscipula", common: "Venus flytrap" },
  { name: "Cannabis sativa", common: "Cannabis" },
  { name: "Solanum lycopersicum", common: "Tomato" },
  { name: "Solanum tuberosum", common: "Potato" },
  { name: "Oryza sativa", common: "Rice" },
  { name: "Triticum aestivum", common: "Bread wheat" },
  { name: "Zea mays", common: "Maize" },
  { name: "Coffea arabica", common: "Arabica coffee" },
  { name: "Vitis vinifera", common: "Grapevine" },
  { name: "Malus domestica", common: "Apple" },
  { name: "Taraxacum officinale", common: "Dandelion" },
  { name: "Cocos nucifera", common: "Coconut palm" },
  { name: "Musa acuminata", common: "Banana" },
  { name: "Carnegiea gigantea", common: "Saguaro" },
  // Fungi
  { name: "Amanita muscaria", common: "Fly agaric" },
  { name: "Agaricus bisporus", common: "Button mushroom" },
  { name: "Amanita phalloides", common: "Death cap" },
  { name: "Lentinula edodes", common: "Shiitake" },
  { name: "Tuber melanosporum", common: "Black truffle" },

  // ---- Within-clade depth for harder Kinship boards ----
  // Famous species that rank too low in occurrence for densification to reach, but
  // fill out recognisable sub-clades so a "within X" board has four groups of four.
  // (Dolphins/Panthera/dabbling-duck bases already exist above or in the anchors.)

  // Whales (Cetacea): rorquals · right whales · beaked whales · porpoises
  { name: "Balaenoptera physalus", common: "Fin whale" },
  { name: "Balaenoptera acutorostrata", common: "Minke whale" },
  { name: "Balaenoptera borealis", common: "Sei whale" },
  { name: "Eubalaena glacialis", common: "North Atlantic right whale" },
  { name: "Eubalaena australis", common: "Southern right whale" },
  { name: "Eubalaena japonica", common: "North Pacific right whale" },
  { name: "Balaena mysticetus", common: "Bowhead whale" },
  { name: "Ziphius cavirostris", common: "Cuvier's beaked whale" },
  { name: "Hyperoodon ampullatus", common: "Northern bottlenose whale" },
  { name: "Berardius bairdii", common: "Baird's beaked whale" },
  { name: "Mesoplodon densirostris", common: "Blainville's beaked whale" },
  { name: "Phocoena phocoena", common: "Harbour porpoise" },
  { name: "Phocoenoides dalli", common: "Dall's porpoise" },
  { name: "Neophocaena asiaeorientalis", common: "Finless porpoise" },
  { name: "Phocoena sinus", common: "Vaquita" }, // Phocoenidae 3→4 → 4th whale group

  // Cats (Felidae): small cats · lynxes · ocelots (+ big cats already present)
  { name: "Felis silvestris", common: "Wildcat" },
  { name: "Felis chaus", common: "Jungle cat" },
  { name: "Felis nigripes", common: "Black-footed cat" },
  { name: "Felis margarita", common: "Sand cat" },
  { name: "Lynx rufus", common: "Bobcat" },
  { name: "Lynx canadensis", common: "Canada lynx" },
  { name: "Lynx pardinus", common: "Iberian lynx" },
  { name: "Leopardus pardalis", common: "Ocelot" },
  { name: "Leopardus wiedii", common: "Margay" },
  { name: "Leopardus geoffroyi", common: "Geoffroy's cat" },
  { name: "Leopardus tigrinus", common: "Oncilla" },
  { name: "Prionailurus bengalensis", common: "Leopard cat" },
  { name: "Prionailurus viverrinus", common: "Fishing cat" },
  { name: "Caracal caracal", common: "Caracal" },
  { name: "Leptailurus serval", common: "Serval" },
  { name: "Neofelis nebulosa", common: "Clouded leopard" },
  { name: "Otocolobus manul", common: "Pallas's cat" }, // +4 cats push Felidae >25 leaves
  { name: "Herpailurus yagouaroundi", common: "Jaguarundi" }, // so grid descends to
  { name: "Catopuma temminckii", common: "Asian golden cat" }, // Panthera|Felis|Lynx|Leopardus
  { name: "Prionailurus rubiginosus", common: "Rusty-spotted cat" },

  // Ducks (Anatidae): dabbling ducks · diving ducks · sea ducks (+ geese/swans base)
  { name: "Anas crecca", common: "Eurasian teal" },
  { name: "Anas acuta", common: "Northern pintail" },
  { name: "Spatula clypeata", common: "Northern shoveler" },
  { name: "Spatula discors", common: "Blue-winged teal" },
  { name: "Mareca strepera", common: "Gadwall" },
  { name: "Aythya ferina", common: "Common pochard" },
  { name: "Aythya fuligula", common: "Tufted duck" },
  { name: "Aythya marila", common: "Greater scaup" },
  { name: "Aythya americana", common: "Redhead" },
  { name: "Aythya valisineria", common: "Canvasback" },
  { name: "Mergus merganser", common: "Common merganser" },
  { name: "Mergus serrator", common: "Red-breasted merganser" },
  { name: "Bucephala clangula", common: "Common goldeneye" },
  { name: "Bucephala albeola", common: "Bufflehead" },
  { name: "Somateria mollissima", common: "Common eider" },
  { name: "Melanitta nigra", common: "Common scoter" },

  // Dogs (Canidae): true foxes · wolves & jackals · South American canids
  { name: "Vulpes velox", common: "Swift fox" },
  { name: "Vulpes macrotis", common: "Kit fox" },
  { name: "Vulpes corsac", common: "Corsac fox" },
  { name: "Canis aureus", common: "Golden jackal" },
  { name: "Canis mesomelas", common: "Black-backed jackal" },
  { name: "Canis lupaster", common: "African golden wolf" },
  { name: "Canis simensis", common: "Ethiopian wolf" },
  { name: "Lycalopex culpaeus", common: "Culpeo" },
  { name: "Lycalopex gymnocercus", common: "Pampas fox" },
  { name: "Cerdocyon thous", common: "Crab-eating fox" },
  { name: "Chrysocyon brachyurus", common: "Maned wolf" },
  { name: "Speothos venaticus", common: "Bush dog" },
  { name: "Nyctereutes procyonoides", common: "Raccoon dog" },
  { name: "Otocyon megalotis", common: "Bat-eared fox" },
  { name: "Urocyon cinereoargenteus", common: "Gray fox" },
];
