// Out-of-set guess index.
//
// The playable/answer set is curated, but a player can guess ANY organism. This
// module maps a typed name to a graft payload (the species + whatever ancestor
// clades we're missing, with a connection point that already exists in the tree),
// so an out-of-set guess lands informatively — see src/core/graft.ts.
//
// The bulk of the index is GENERATED by scripts/build-guess-index.mjs (GBIF sweep
// → OTL lineage → trimmed at the first shipped ancestor) and bundled as JSON. A
// couple of curated extras can be appended below. The eventual DB-backed
// search_taxa RPC replaces the bundled JSON for the full-scale universe.

import { normalizeName, type GraftTaxon } from "../core";
import generated from "./guessIndex.generated.json";

interface IndexEntry {
  graft: GraftTaxon;
  /** Normalized names/synonyms this entry answers to. */
  keys: string[];
}

// Hand-curated extras (added on top of the generated sweep). Keys are normalized
// at load. Skipped if the sweep already covers the same first key.
const EXTRAS: IndexEntry[] = [
  {
    keys: ["okapi", "okapia johnstoni", "forest giraffe"],
    graft: {
      id: "oos:okapia-johnstoni", sciName: "Okapia johnstoni", common: "Okapi", rank: "species",
      lineage: [{ id: "ott768685", sciName: "Giraffidae", rank: "family" }],
    },
  },
].map((e) => ({ ...e, keys: e.keys.map(normalizeName) }));

const GENERATED = (generated.entries as IndexEntry[]) ?? [];

// Generated first; curated extras only if their primary key isn't already covered.
const SAMPLE: IndexEntry[] = (() => {
  const firstKeys = new Set(GENERATED.map((e) => e.keys[0]));
  return [...GENERATED, ...EXTRAS.filter((e) => !firstKeys.has(e.keys[0]))];
})();

/** A typeahead hit for an out-of-set organism (rendered below in-set matches). */
export interface OutOfSetHit { id: string; common: string; sci: string; }

/** Out-of-set organisms whose name matches `query`, prefix hits before substring
 *  hits. Empty query returns nothing (the browse list stays in-set only). */
export function searchOutOfSet(query: string, limit = 4): OutOfSetHit[] {
  const q = normalizeName(query);
  if (!q) return [];
  const pre: OutOfSetHit[] = [];
  const sub: OutOfSetHit[] = [];
  for (const e of SAMPLE) {
    const hit: OutOfSetHit = { id: e.graft.id, common: e.graft.common ?? e.graft.sciName, sci: e.graft.sciName };
    if (e.keys.some((k) => k.startsWith(q))) pre.push(hit);
    else if (e.keys.some((k) => k.includes(q))) sub.push(hit);
  }
  return [...pre, ...sub].slice(0, limit);
}

/** Resolve typed text (or the "Common (Scientific)" autocomplete form) to a graft
 *  payload, or null if it's not a known out-of-set organism. */
export function resolveOutOfSet(text: string): GraftTaxon | null {
  const combined = text.match(/^\s*(.*?)\s*\(([^()]+)\)\s*$/);
  const queries = combined ? [combined[1], combined[2], text] : [text];
  for (const raw of queries) {
    const q = normalizeName(raw);
    if (!q) continue;
    const e = SAMPLE.find((entry) => entry.keys.includes(q));
    if (e) return e.graft;
  }
  return null;
}
